dist: trusty
sudo: required

language: ruby
rvm:
  - 2.5.5
  - 2.6.5
  - ruby-head

jobs:
  allow_failures:
  - rvm: ruby-head

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - gem install bundler -v 2.0.2

cache:
  directories:
    - $HOME/.rvm
    - $HOME/bundle

bundler_args: --without production development --path $HOME/bundle

before_script:
  - psql -c 'CREATE DATABASE inspirer_test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - cp .env.travis .env
  - bundle exec rake db:migrate
  - make install_linters

script:
  - make test
  - brakeman -A -z
  - bundle audit update && bundle audit check
  - rubocop -DSE --force-exclusion -c .rubocop.yml
  - bundle exec rake unused_routes
  - bundle exec bin/rails zeitwerk:check
  - bundle exec bin/rails db:seed

services:
  - postgresql
  - redis-server

addons:
  postgresql: '11.2'
