version: '3'

services:
  app:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - default

  db:
    image: postgres:10
    volumes:
      - .data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default

networks:
  default:
