default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>

development:
  <<: *default
  database: inspirer_development
  host: db

test:
  <<: *default
  database: inspirer_test
  host: <%= ENV.fetch('DB_HOST', 'db') %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') %>
  host: localhost
